package jcbhmr:go@1.24.5-rc1;

interface builtin {
    
        
    resource any {}

    resource complex128 {}

    resource complex64 {}

    resource error {
        error2: func() -> string;
    }
}
