package jcbhmr:go@1.24.5-rc1;

/// # Constants
/// 
///         const (
///         	Layout      = "01/02 03:04:05PM '06 -0700" // The reference time, in numerical order.
///         	ANSIC       = "Mon Jan _2 15:04:05 2006"
///         	UnixDate    = "Mon Jan _2 15:04:05 MST 2006"
///         	RubyDate    = "Mon Jan 02 15:04:05 -0700 2006"
///         	RFC822      = "02 Jan 06 15:04 MST"
///         	RFC822Z     = "02 Jan 06 15:04 -0700" // RFC822 with numeric zone
///         	RFC850      = "Monday, 02-Jan-06 15:04:05 MST"
///         	RFC1123     = "Mon, 02 Jan 2006 15:04:05 MST"
///         	RFC1123Z    = "Mon, 02 Jan 2006 15:04:05 -0700" // RFC1123 with numeric zone
///         	RFC3339     = "2006-01-02T15:04:05Z07:00"
///         	RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
///         	Kitchen     = "3:04PM"
///         	// Handy time stamps.
///         	Stamp      = "Jan _2 15:04:05"
///         	StampMilli = "Jan _2 15:04:05.000"
///         	StampMicro = "Jan _2 15:04:05.000000"
///         	StampNano  = "Jan _2 15:04:05.000000000"
///         	DateTime   = "2006-01-02 15:04:05"
///         	DateOnly   = "2006-01-02"
///         	TimeOnly   = "15:04:05"
///         )
/// 
/// These are predefined layouts for use in Time.Format and time.Parse. The reference time used in these layouts is the specific time stamp:
/// 
///         01/02 03:04:05PM '06 -0700
/// 
/// (January 2, 15:04:05, 2006, in time zone seven hours west of GMT). That value is recorded as the constant named Layout, listed below. As a Unix time, this is 1136239445. Since MST is GMT-0700, the reference would be printed by the Unix date command as:
/// 
///         Mon Jan 2 15:04:05 MST 2006
/// 
/// It is a regrettable historic error that the date uses the American convention of putting the numerical month before the day.
/// 
/// The example for Time.Format demonstrates the working of the layout string in detail and is a good reference.
/// 
/// Note that the RFC822, RFC850, and RFC1123 formats should be applied only to local times. Applying them to UTC times will use "UTC" as the time zone abbreviation, while strictly speaking those RFCs require the use of "GMT" in that case. When using the RFC1123 or RFC1123Z formats for parsing, note that these formats define a leading zero for the day-in-month portion, which is not strictly allowed by RFC 1123. This will result in an error when parsing date strings that occur in the first 9 days of a given month. In general RFC1123Z should be used instead of RFC1123 for servers that insist on that format, and RFC3339 should be preferred for new protocols. RFC3339, RFC822, RFC822Z, RFC1123, and RFC1123Z are useful for formatting; when used with time.Parse they do not accept all the time formats permitted by the RFCs and they do accept time formats not formally defined. The RFC3339Nano format removes trailing zeros from the seconds field and thus may not sort correctly once formatted.
/// 
/// Most programs can use one of the defined constants as the layout passed to Format or Parse. The rest of this comment can be ignored unless you are creating a custom layout string.
/// 
/// To define your own format, write down what the reference time would look like formatted your way; see the values of constants like ANSIC, StampMicro or Kitchen for examples. The model is to demonstrate what the reference time looks like so that the Format and Parse methods can apply the same transformation to a general time value.
/// 
/// Here is a summary of the components of a layout string. Each element shows by example the formatting of an element of the reference time. Only these values are recognized. Text in the layout string that is not recognized as part of the reference time is echoed verbatim during Format and expected to appear verbatim in the input to Parse.
/// 
///         Year: "2006" "06"
///         Month: "Jan" "January" "01" "1"
///         Day of the week: "Mon" "Monday"
///         Day of the month: "2" "_2" "02"
///         Day of the year: "__2" "002"
///         Hour: "15" "3" "03" (PM or AM)
///         Minute: "4" "04"
///         Second: "5" "05"
///         AM/PM mark: "PM"
/// 
/// Numeric time zone offsets format as follows:
/// 
///         "-0700"     ±hhmm
///         "-07:00"    ±hh:mm
///         "-07"       ±hh
///         "-070000"   ±hhmmss
///         "-07:00:00" ±hh:mm:ss
/// 
/// Replacing the sign in the format with a Z triggers the ISO 8601 behavior of printing Z instead of an offset for the UTC zone. Thus:
/// 
///         "Z0700"      Z or ±hhmm
///         "Z07:00"     Z or ±hh:mm
///         "Z07"        Z or ±hh
///         "Z070000"    Z or ±hhmmss
///         "Z07:00:00"  Z or ±hh:mm:ss
/// 
/// Within the format string, the underscores in `"_2"` and `"__2"` represent spaces that may be replaced by digits if the following number has multiple digits, for compatibility with fixed-width Unix time formats. A leading zero represents a zero-padded value.
/// 
/// The formats `__2` and 002 are space-padded and zero-padded three-character day of year; there is no unpadded day of year format.
/// 
/// A comma or decimal point followed by one or more zeros represents a fractional second, printed to the given number of decimal places. A comma or decimal point followed by one or more nines represents a fractional second, printed to the given number of decimal places, with trailing zeros removed. For example "15:04:05,000" or "15:04:05.000" formats or parses with millisecond precision.
/// 
/// Some valid layouts are invalid time values for time.Parse, due to formats such as _ for space padding and Z for zone information.
/// 
///         const (
///         	Nanosecond  Duration = 1
///         	Microsecond          = 1000 * Nanosecond
///         	Millisecond          = 1000 * Microsecond
///         	Second               = 1000 * Millisecond
///         	Minute               = 60 * Second
///         	Hour                 = 60 * Minute
///         )
/// 
/// Common durations. There is no definition for units of Day or larger to avoid confusion across daylight savings time zone transitions.
/// 
/// To count the number of units in a Duration, divide:
/// 
///         second := time.Second
///         fmt.Print(int64(second/time.Millisecond)) // prints 1000
/// 
/// To convert an integer number of units to a Duration, multiply:
/// 
///         seconds := 10
///         fmt.Print(time.Duration(seconds)*time.Second) // prints 10s
interface time {
    use builtin.{error};

    /// The reference time, in numerical order.
    layout: func() -> string;
    ANSIC: func() -> string;
    unix-date: func() -> string;
    ruby-date: func() -> string;
    RFC822: func() -> string;
    /// RFC822 with numeric zone
    RFC822Z: func() -> string;
    RFC850: func() -> string;
    RFC1123: func() -> string;
    /// RFC1123 with numeric zone
    RFC1123Z: func() -> string;
    RFC3339: func() -> string;
    RFC3339-nano: func() -> string;
    kitchen: func() -> string;
    stamp: func() -> string;
    stamp-milli: func() -> string;
    stamp-micro: func() -> string;
    stamp-nano: func() -> string;
    date-time: func() -> string;
    date-only: func() -> string;
    time-only: func() -> string;

    nanosecond: func() -> duration;
    microsecond: func() -> duration;
    millisecond: func() -> duration;
    second: func() -> duration;
    minute: func() -> duration;
    hour: func() -> duration;

    // after: func(d: duration) -> chan<time>;

    /// Sleep pauses the current goroutine for at least the duration d. A negative or zero duration causes Sleep to return immediately.
    sleep: func(d: duration);

    // tick: func(d: duration) -> chan<time>;

    /// A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.
    type duration = s64;

    /// ParseDuration parses a duration string. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    parse-duration: func(s: string) -> result<duration, error>;

    /// Since returns the time elapsed since t. It is shorthand for time.Now().Sub(t).
    since: func(t: time) -> duration;

    /// Until returns the duration until t. It is shorthand for t.Sub(time.Now()).
    until: func(t: time) -> duration;

    /// Abs returns the absolute value of d. As a special case, Duration(math.MinInt64) is converted to Duration(math.MaxInt64), reducing its magnitude by 1 nanosecond.
    duration-abs: func(self: duration) -> duration;

    /// Hours returns the duration as a floating point number of hours.
    duration-hours: func(self: duration) -> f64;

    /// Microseconds returns the duration as an integer microsecond count.
    duration-microseconds: func(self: duration) -> s64;

    /// Milliseconds returns the duration as an integer millisecond count.
    duration-milliseconds: func(self: duration) -> s64;

    /// Minutes returns the duration as a floating point number of minutes.
    duration-minutes: func(self: duration) -> f64;

    /// Nanoseconds returns the duration as an integer nanosecond count.
    duration-nanoseconds: func(self: duration) -> s64;

    /// Round returns the result of rounding d to the nearest multiple of m. The rounding behavior for halfway values is to round away from zero. If the result exceeds the maximum (or minimum) value that can be stored in a Duration, Round returns the maximum (or minimum) duration. If m <= 0, Round returns d unchanged.
    duration-round: func(self: duration, m: duration) -> duration;

    /// Seconds returns the duration as a floating point number of seconds.
    duration-seconds: func(self: duration) -> f64;

    /// String returns a string representing the duration in the form "72h3m0.5s". Leading zero units are omitted. As a special case, durations less than one second format use a smaller unit (milli-, micro-, or nanoseconds) to ensure that the leading digit is non-zero. The zero duration formats as 0s.
    duration-string: func(self: duration) -> string;

    /// Truncate returns the result of rounding d toward zero to a multiple of m. If m <= 0, Truncate returns d unchanged.
    duration-truncate: func(self: duration, m: duration) -> duration;

    /// A Location maps time instants to the zone in use at that time. Typically, the Location represents the collection of time offsets in use in a geographical area. For many Locations the time offset varies depending on whether daylight savings time is in use at the time instant.
    ///
    /// Location is used to provide a time zone in a printed Time value and for calculations involving intervals that may cross daylight savings time boundaries.
    resource location {
        constructor();

        /// String returns a descriptive name for the time zone information, corresponding to the name argument to LoadLocation or FixedZone.
        %string: func() -> string;
    }

    /// Local represents the system's local time zone. On Unix systems, Local consults the TZ environment variable to find the time zone to use. No TZ means use the system default /etc/localtime. TZ="" means use UTC. TZ="foo" means use file foo in the system timezone directory.
    local: func() -> location;

    /// UTC represents Universal Coordinated Time (UTC).
    UTC: func() -> location;

    /// FixedZone returns a Location that always uses the given zone name and offset (seconds east of UTC).
    fixed-zone: func(name: string, offset: s32) -> location;
    
    /// LoadLocation returns the Location with the given name.
    /// 
    /// If the name is "" or "UTC", LoadLocation returns UTC. If the name is "Local", LoadLocation returns Local.
    /// 
    /// Otherwise, the name is taken to be a location name corresponding to a file in the IANA Time Zone database, such as "America/New_York".
    /// 
    /// LoadLocation looks for the IANA Time Zone database in the following locations in order:
    /// 
    /// - the directory or uncompressed zip file named by the ZONEINFO environment variable
    /// - on a Unix system, the system standard installation location
    /// - $GOROOT/lib/time/zoneinfo.zip
    /// - the time/tzdata package, if it was imported
    load-location: func(name: string) -> result<location, error>;

    /// LoadLocationFromTZData returns a Location with the given name initialized from the IANA Time Zone database-formatted data. The data should be in the format of a standard IANA time zone file (for example, the content of /etc/localtime on Unix systems).
    load-location-from-TZ-data: func(name: string, data: list<u8>) -> result<location, error>;

    /// A Month specifies a month of the year (January = 1, ...).
    /// 
    ///         const (
    ///         	January Month = 1 + iota
    ///         	February
    ///         	March
    ///         	April
    ///         	May
    ///         	June
    ///         	July
    ///         	August
    ///         	September
    ///         	October
    ///         	November
    ///         	December
    ///         )
    type month = s32;
    january: func() -> month;
    february: func() -> month;
    march: func() -> month;
    april: func() -> month;
    may: func() -> month;
    june: func() -> month;
    july: func() -> month;
    august: func() -> month;
    september: func() -> month;
    october: func() -> month;
    november: func() -> month;
    december: func() -> month;

    /// String returns the English name of the month ("January", "February", ...).
    month-string: func(self: month) -> string;

    /// A Time represents an instant in time with nanosecond precision.
    /// 
    /// Programs using times should typically store and pass them as values, not pointers. That is, time variables and struct fields should be of type time.Time, not *time.Time.
    /// 
    /// A Time value can be used by multiple goroutines simultaneously except that the methods Time.GobDecode, Time.UnmarshalBinary, Time.UnmarshalJSON and Time.UnmarshalText are not concurrency-safe.
    /// 
    /// Time instants can be compared using the Time.Before, Time.After, and Time.Equal methods. The Time.Sub method subtracts two instants, producing a Duration. The Time.Add method adds a Time and a Duration, producing a Time.
    /// 
    /// The zero value of type Time is January 1, year 1, 00:00:00.000000000 UTC. As this time is unlikely to come up in practice, the Time.IsZero method gives a simple way of detecting a time that has not been initialized explicitly.
    /// 
    /// Each time has an associated Location. The methods Time.Local, Time.UTC, and Time.In return a Time with a specific Location. Changing the Location of a Time value with these methods does not change the actual instant it represents, only the time zone in which to interpret it.
    /// 
    /// Representations of a Time value saved by the Time.GobEncode, Time.MarshalBinary, Time.AppendBinary, Time.MarshalJSON, Time.MarshalText and Time.AppendText methods store the Time.Location's offset, but not the location name. They therefore lose information about Daylight Saving Time.
    /// 
    /// In addition to the required “wall clock” reading, a Time may contain an optional reading of the current process's monotonic clock, to provide additional precision for comparison or subtraction. See the “Monotonic Clocks” section in the package documentation for details.
    /// 
    /// Note that the Go == operator compares not just the time instant but also the Location and the monotonic clock reading. Therefore, Time values should not be used as map or database keys without first guaranteeing that the identical Location has been set for all values, which can be achieved through use of the UTC or Local method, and that the monotonic clock reading has been stripped by setting t = t.Round(0). In general, prefer t.Equal(u) to t == u, since t.Equal uses the most accurate comparison available and correctly handles the case when only one of its arguments has a monotonic clock reading.
    resource time {
        constructor();

        format: func(layout: string) -> string;
    }

    /// Date returns the Time corresponding to
    /// 
    ///         yyyy-mm-dd hh:mm:ss + nsec nanoseconds
    /// 
    /// in the appropriate zone for that time in the given location.
    /// 
    /// The month, day, hour, min, sec, and nsec values may be outside their usual ranges and will be normalized during the conversion. For example, October 32 converts to November 1.
    /// 
    /// A daylight savings time transition skips or repeats times. For example, in the United States, March 13, 2011 2:15am never occurred, while November 6, 2011 1:15am occurred twice. In such cases, the choice of time zone, and therefore the time, is not well-defined. Date returns a time that is correct in one of the two zones involved in the transition, but it does not guarantee which.
    /// 
    /// Date panics if loc is nil.
    date: func(year: s32, month: month, day: s32, hour: s32, min: s32, sec: s32, nsec: s32, loc: location) -> time;

    /// Now returns the current local time.
    now: func() -> time;

    /// Parse parses a formatted string and returns the time value it represents. See the documentation for the constant called Layout to see how to represent the format. The second argument must be parseable using the format string (layout) provided as the first argument.
    /// 
    /// The example for Time.Format demonstrates the working of the layout string in detail and is a good reference.
    /// 
    /// When parsing (only), the input may contain a fractional second field immediately after the seconds field, even if the layout does not signify its presence. In that case either a comma or a decimal point followed by a maximal series of digits is parsed as a fractional second. Fractional seconds are truncated to nanosecond precision.
    /// 
    /// Elements omitted from the layout are assumed to be zero or, when zero is impossible, one, so parsing "3:04pm" returns the time corresponding to Jan 1, year 0, 15:04:00 UTC (note that because the year is 0, this time is before the zero Time). Years must be in the range 0000..9999. The day of the week is checked for syntax but it is otherwise ignored.
    /// 
    /// For layouts specifying the two-digit year 06, a value NN >= 69 will be treated as 19NN and a value NN < 69 will be treated as 20NN.
    /// 
    /// The remainder of this comment describes the handling of time zones.
    /// 
    /// In the absence of a time zone indicator, Parse returns a time in UTC.
    /// 
    /// When parsing a time with a zone offset like -0700, if the offset corresponds to a time zone used by the current location (Local), then Parse uses that location and zone in the returned time. Otherwise it records the time as being in a fabricated location with time fixed at the given zone offset.
    /// 
    /// When parsing a time with a zone abbreviation like MST, if the zone abbreviation has a defined offset in the current location, then that offset is used. The zone abbreviation "UTC" is recognized as UTC regardless of location. If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset. This choice means that such a time can be parsed and reformatted with the same layout losslessly, but the exact instant used in the representation will differ by the actual zone offset. To avoid such problems, prefer time layouts that use a numeric zone offset, or use ParseInLocation.
    parse: func(layout: string, value: string) -> result<time, error>;

    /// ParseInLocation is like Parse but differs in two important ways. First, in the absence of time zone information, Parse interprets a time as UTC; ParseInLocation interprets the time as in the given location. Second, when given a zone offset or abbreviation, Parse tries to match it against the Local location; ParseInLocation uses the given location.
    parse-in-location: func(layout: string, value: string, loc: location) -> result<time, error>;
}
