// Code generated by wit-bindgen-go. DO NOT EDIT.

package time

import (
	"go.bytecodealliance.org/cm"
)

func lift_OptionLocation(f0 uint32, f1 uint32) (v cm.Option[Location]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[Location])(cm.Some[Location](cm.Reinterpret[Location]((uint32)(f1))))
}
