// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package time represents the exported interface "jcbhmr:go/time@1.24.5-rc1".
//
// # Constants
//
// const (
//
//	Layout      = "01/02 03:04:05PM '06 -0700" // The reference time, in numerical
//
// order.
//
//	ANSIC       = "Mon Jan _2 15:04:05 2006"
//	UnixDate    = "Mon Jan _2 15:04:05 MST 2006"
//	RubyDate    = "Mon Jan 02 15:04:05 -0700 2006"
//	RFC822      = "02 Jan 06 15:04 MST"
//	RFC822Z     = "02 Jan 06 15:04 -0700" // RFC822 with numeric zone
//	RFC850      = "Monday, 02-Jan-06 15:04:05 MST"
//	RFC1123     = "Mon, 02 Jan 2006 15:04:05 MST"
//	RFC1123Z    = "Mon, 02 Jan 2006 15:04:05 -0700" // RFC1123 with numeric zone
//	RFC3339     = "2006-01-02T15:04:05Z07:00"
//	RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
//	Kitchen     = "3:04PM"
//	// Handy time stamps.
//	Stamp      = "Jan _2 15:04:05"
//	StampMilli = "Jan _2 15:04:05.000"
//	StampMicro = "Jan _2 15:04:05.000000"
//	StampNano  = "Jan _2 15:04:05.000000000"
//	DateTime   = "2006-01-02 15:04:05"
//	DateOnly   = "2006-01-02"
//	TimeOnly   = "15:04:05"
//
// )
//
// These are predefined layouts for use in Time.Format and time.Parse. The reference
// time used in these layouts is the specific time stamp:
//
// 01/02 03:04:05PM '06 -0700
//
// (January 2, 15:04:05, 2006, in time zone seven hours west of GMT). That value is
// recorded as the constant named Layout, listed below. As a Unix time, this is 1136239445.
// Since MST is GMT-0700, the reference would be printed by the Unix date command
// as:
//
// Mon Jan 2 15:04:05 MST 2006
//
// It is a regrettable historic error that the date uses the American convention of
// putting the numerical month before the day.
//
// The example for Time.Format demonstrates the working of the layout string in detail
// and is a good reference.
//
// Note that the RFC822, RFC850, and RFC1123 formats should be applied only to local
// times. Applying them to UTC times will use "UTC" as the time zone abbreviation,
// while strictly speaking those RFCs require the use of "GMT" in that case. When
// using the RFC1123 or RFC1123Z formats for parsing, note that these formats define
// a leading zero for the day-in-month portion, which is not strictly allowed by RFC
// 1123. This will result in an error when parsing date strings that occur in the
// first 9 days of a given month. In general RFC1123Z should be used instead of RFC1123
// for servers that insist on that format, and RFC3339 should be preferred for new
// protocols. RFC3339, RFC822, RFC822Z, RFC1123, and RFC1123Z are useful for formatting;
// when used with time.Parse they do not accept all the time formats permitted by
// the RFCs and they do accept time formats not formally defined. The RFC3339Nano
// format removes trailing zeros from the seconds field and thus may not sort correctly
// once formatted.
//
// Most programs can use one of the defined constants as the layout passed to Format
// or Parse. The rest of this comment can be ignored unless you are creating a custom
// layout string.
//
// To define your own format, write down what the reference time would look like formatted
// your way; see the values of constants like ANSIC, StampMicro or Kitchen for examples.
// The model is to demonstrate what the reference time looks like so that the Format
// and Parse methods can apply the same transformation to a general time value.
//
// Here is a summary of the components of a layout string. Each element shows by example
// the formatting of an element of the reference time. Only these values are recognized.
// Text in the layout string that is not recognized as part of the reference time
// is echoed verbatim during Format and expected to appear verbatim in the input to
// Parse.
//
// Year: "2006" "06"
// Month: "Jan" "January" "01" "1"
// Day of the week: "Mon" "Monday"
// Day of the month: "2" "_2" "02"
// Day of the year: "__2" "002"
// Hour: "15" "3" "03" (PM or AM)
// Minute: "4" "04"
// Second: "5" "05"
// AM/PM mark: "PM"
//
// Numeric time zone offsets format as follows:
//
// "-0700"     ±hhmm
// "-07:00"    ±hh:mm
// "-07"       ±hh
// "-070000"   ±hhmmss
// "-07:00:00" ±hh:mm:ss
//
// Replacing the sign in the format with a Z triggers the ISO 8601 behavior of printing
// Z instead of an offset for the UTC zone. Thus:
//
// "Z0700"      Z or ±hhmm
// "Z07:00"     Z or ±hh:mm
// "Z07"        Z or ±hh
// "Z070000"    Z or ±hhmmss
// "Z07:00:00"  Z or ±hh:mm:ss
//
// Within the format string, the underscores in `"_2"` and `"__2"` represent spaces
// that may be replaced by digits if the following number has multiple digits, for
// compatibility with fixed-width Unix time formats. A leading zero represents a zero-padded
// value.
//
// The formats `__2` and 002 are space-padded and zero-padded three-character day
// of year; there is no unpadded day of year format.
//
// A comma or decimal point followed by one or more zeros represents a fractional
// second, printed to the given number of decimal places. A comma or decimal point
// followed by one or more nines represents a fractional second, printed to the given
// number of decimal places, with trailing zeros removed. For example "15:04:05,000"
// or "15:04:05.000" formats or parses with millisecond precision.
//
// Some valid layouts are invalid time values for time.Parse, due to formats such
// as _ for space padding and Z for zone information.
//
// const (
//
//	Nanosecond  Duration = 1
//	Microsecond          = 1000 * Nanosecond
//	Millisecond          = 1000 * Microsecond
//	Second               = 1000 * Millisecond
//	Minute               = 60 * Second
//	Hour                 = 60 * Minute
//
// )
//
// Common durations. There is no definition for units of Day or larger to avoid confusion
// across daylight savings time zone transitions.
//
// To count the number of units in a Duration, divide:
//
// second := time.Second
// fmt.Print(int64(second/time.Millisecond)) // prints 1000
//
// To convert an integer number of units to a Duration, multiply:
//
// seconds := 10
// fmt.Print(time.Duration(seconds)*time.Second) // prints 10s
package time

import (
	"github.com/jcbhmr/go-wasm/builtin"
	"go.bytecodealliance.org/cm"
)

// Error represents the exported type alias "jcbhmr:go/time@1.24.5-rc1#error".
//
// See [builtin.Error] for more information.
type Error = builtin.Error

// Duration represents the s64 "jcbhmr:go/time@1.24.5-rc1#duration".
//
// tick: func(d: duration) -> chan<time>;
// A Duration represents the elapsed time between two instants as an int64 nanosecond
// count. The representation limits the largest representable duration to approximately
// 290 years.
//
//	type duration = s64
type Duration int64

// Location represents the exported resource "jcbhmr:go/time@1.24.5-rc1#location".
//
// A Location maps time instants to the zone in use at that time. Typically, the Location
// represents the collection of time offsets in use in a geographical area. For many
// Locations the time offset varies depending on whether daylight savings time is
// in use at the time instant.
//
// Location is used to provide a time zone in a printed Time value and for calculations
// involving intervals that may cross daylight savings time boundaries.
//
//	resource location
type Location cm.Resource

// LocationResourceNew represents the imported resource-new for resource "location".
//
// Creates a new resource handle.
//
//go:nosplit
func LocationResourceNew(rep cm.Rep) (result Location) {
	rep0 := cm.Reinterpret[uint32](rep)
	result0 := wasmimport_LocationResourceNew((uint32)(rep0))
	result = cm.Reinterpret[Location]((uint32)(result0))
	return
}

// ResourceRep represents the imported resource-rep for resource "location".
//
// Returns the underlying resource representation.
//
//go:nosplit
func (self Location) ResourceRep() (result cm.Rep) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_LocationResourceRep((uint32)(self0))
	result = cm.Reinterpret[cm.Rep]((uint32)(result0))
	return
}

// ResourceDrop represents the imported resource-drop for resource "location".
//
// Drops a resource handle.
//
//go:nosplit
func (self Location) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_LocationResourceDrop((uint32)(self0))
	return
}

func init() {
	Exports.Location.Destructor = func(self cm.Rep) {}
}

// Month represents the s32 "jcbhmr:go/time@1.24.5-rc1#month".
//
// A Month specifies a month of the year (January = 1, ...).
//
// const (
//
//	January Month = 1 + iota
//	February
//	March
//	April
//	May
//	June
//	July
//	August
//	September
//	October
//	November
//	December
//
// )
//
//	type month = s32
type Month int32

// Time represents the exported resource "jcbhmr:go/time@1.24.5-rc1#time".
//
// A Time represents an instant in time with nanosecond precision.
//
// Programs using times should typically store and pass them as values, not pointers.
// That is, time variables and struct fields should be of type time.Time, not *time.Time.
//
// A Time value can be used by multiple goroutines simultaneously except that the
// methods Time.GobDecode, Time.UnmarshalBinary, Time.UnmarshalJSON and Time.UnmarshalText
// are not concurrency-safe.
//
// Time instants can be compared using the Time.Before, Time.After, and Time.Equal
// methods. The Time.Sub method subtracts two instants, producing a Duration. The
// Time.Add method adds a Time and a Duration, producing a Time.
//
// The zero value of type Time is January 1, year 1, 00:00:00.000000000 UTC. As this
// time is unlikely to come up in practice, the Time.IsZero method gives a simple
// way of detecting a time that has not been initialized explicitly.
//
// Each time has an associated Location. The methods Time.Local, Time.UTC, and Time.In
// return a Time with a specific Location. Changing the Location of a Time value with
// these methods does not change the actual instant it represents, only the time zone
// in which to interpret it.
//
// Representations of a Time value saved by the Time.GobEncode, Time.MarshalBinary,
// Time.AppendBinary, Time.MarshalJSON, Time.MarshalText and Time.AppendText methods
// store the Time.Location's offset, but not the location name. They therefore lose
// information about Daylight Saving Time.
//
// In addition to the required “wall clock” reading, a Time may contain an optional
// reading of the current process's monotonic clock, to provide additional precision
// for comparison or subtraction. See the “Monotonic Clocks” section in the package
// documentation for details.
//
// Note that the Go == operator compares not just the time instant but also the Location
// and the monotonic clock reading. Therefore, Time values should not be used as map
// or database keys without first guaranteeing that the identical Location has been
// set for all values, which can be achieved through use of the UTC or Local method,
// and that the monotonic clock reading has been stripped by setting t = t.Round(0).
// In general, prefer t.Equal(u) to t == u, since t.Equal uses the most accurate comparison
// available and correctly handles the case when only one of its arguments has a monotonic
// clock reading.
//
//	resource time
type Time cm.Resource

// TimeResourceNew represents the imported resource-new for resource "time".
//
// Creates a new resource handle.
//
//go:nosplit
func TimeResourceNew(rep cm.Rep) (result Time) {
	rep0 := cm.Reinterpret[uint32](rep)
	result0 := wasmimport_TimeResourceNew((uint32)(rep0))
	result = cm.Reinterpret[Time]((uint32)(result0))
	return
}

// ResourceRep represents the imported resource-rep for resource "time".
//
// Returns the underlying resource representation.
//
//go:nosplit
func (self Time) ResourceRep() (result cm.Rep) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_TimeResourceRep((uint32)(self0))
	result = cm.Reinterpret[cm.Rep]((uint32)(result0))
	return
}

// ResourceDrop represents the imported resource-drop for resource "time".
//
// Drops a resource handle.
//
//go:nosplit
func (self Time) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_TimeResourceDrop((uint32)(self0))
	return
}

func init() {
	Exports.Time.Destructor = func(self cm.Rep) {}
}
