// Code generated by wit-bindgen-go. DO NOT EDIT.

package time

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "jcbhmr:go@1.24.5-rc1".

//go:wasmimport [export]jcbhmr:go/time@1.24.5-rc1 [resource-new]location
//go:noescape
func wasmimport_LocationResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]jcbhmr:go/time@1.24.5-rc1 [resource-rep]location
//go:noescape
func wasmimport_LocationResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]jcbhmr:go/time@1.24.5-rc1 [resource-drop]location
//go:noescape
func wasmimport_LocationResourceDrop(self0 uint32)

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#[dtor]location
//export jcbhmr:go/time@1.24.5-rc1#[dtor]location
func wasmexport_LocationDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.Location.Destructor(self)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#[constructor]location
//export jcbhmr:go/time@1.24.5-rc1#[constructor]location
func wasmexport_Constructor() (result0 uint32) {
	result := Exports.Location.Constructor()
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#[method]location.string
//export jcbhmr:go/time@1.24.5-rc1#[method]location.string
func wasmexport_LocationString(self0 uint32) (result *string) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	result_ := Exports.Location.String(self)
	result = &result_
	return
}

//go:wasmimport [export]jcbhmr:go/time@1.24.5-rc1 [resource-new]time
//go:noescape
func wasmimport_TimeResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]jcbhmr:go/time@1.24.5-rc1 [resource-rep]time
//go:noescape
func wasmimport_TimeResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]jcbhmr:go/time@1.24.5-rc1 [resource-drop]time
//go:noescape
func wasmimport_TimeResourceDrop(self0 uint32)

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#[dtor]time
//export jcbhmr:go/time@1.24.5-rc1#[dtor]time
func wasmexport_TimeDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.Time.Destructor(self)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#[constructor]time
//export jcbhmr:go/time@1.24.5-rc1#[constructor]time
func wasmexport_Constructor_() (result0 uint32) {
	result := Exports.Time.ExportConstructor()
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#[method]time.format
//export jcbhmr:go/time@1.24.5-rc1#[method]time.format
func wasmexport_TimeFormat(self0 uint32, layout0 *uint8, layout1 uint32) (result *string) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	layout := cm.LiftString[string]((*uint8)(layout0), (uint32)(layout1))
	result_ := Exports.Time.Format(self, layout)
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#layout
//export jcbhmr:go/time@1.24.5-rc1#layout
func wasmexport_Layout() (result *string) {
	result_ := Exports.Layout()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#ANSIC
//export jcbhmr:go/time@1.24.5-rc1#ANSIC
func wasmexport_ANSIC() (result *string) {
	result_ := Exports.ANSIC()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#unix-date
//export jcbhmr:go/time@1.24.5-rc1#unix-date
func wasmexport_UnixDate() (result *string) {
	result_ := Exports.UnixDate()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#ruby-date
//export jcbhmr:go/time@1.24.5-rc1#ruby-date
func wasmexport_RubyDate() (result *string) {
	result_ := Exports.RubyDate()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#RFC822
//export jcbhmr:go/time@1.24.5-rc1#RFC822
func wasmexport_RFC822() (result *string) {
	result_ := Exports.RFC822()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#RFC822Z
//export jcbhmr:go/time@1.24.5-rc1#RFC822Z
func wasmexport_RFC822Z() (result *string) {
	result_ := Exports.RFC822Z()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#RFC850
//export jcbhmr:go/time@1.24.5-rc1#RFC850
func wasmexport_RFC850() (result *string) {
	result_ := Exports.RFC850()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#RFC1123
//export jcbhmr:go/time@1.24.5-rc1#RFC1123
func wasmexport_RFC1123() (result *string) {
	result_ := Exports.RFC1123()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#RFC1123Z
//export jcbhmr:go/time@1.24.5-rc1#RFC1123Z
func wasmexport_RFC1123Z() (result *string) {
	result_ := Exports.RFC1123Z()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#RFC3339
//export jcbhmr:go/time@1.24.5-rc1#RFC3339
func wasmexport_RFC3339() (result *string) {
	result_ := Exports.RFC3339()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#RFC3339-nano
//export jcbhmr:go/time@1.24.5-rc1#RFC3339-nano
func wasmexport_RFC3339Nano() (result *string) {
	result_ := Exports.RFC3339Nano()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#kitchen
//export jcbhmr:go/time@1.24.5-rc1#kitchen
func wasmexport_Kitchen() (result *string) {
	result_ := Exports.Kitchen()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#stamp
//export jcbhmr:go/time@1.24.5-rc1#stamp
func wasmexport_Stamp() (result *string) {
	result_ := Exports.Stamp()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#stamp-milli
//export jcbhmr:go/time@1.24.5-rc1#stamp-milli
func wasmexport_StampMilli() (result *string) {
	result_ := Exports.StampMilli()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#stamp-micro
//export jcbhmr:go/time@1.24.5-rc1#stamp-micro
func wasmexport_StampMicro() (result *string) {
	result_ := Exports.StampMicro()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#stamp-nano
//export jcbhmr:go/time@1.24.5-rc1#stamp-nano
func wasmexport_StampNano() (result *string) {
	result_ := Exports.StampNano()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#date-time
//export jcbhmr:go/time@1.24.5-rc1#date-time
func wasmexport_DateTime() (result *string) {
	result_ := Exports.DateTime()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#date-only
//export jcbhmr:go/time@1.24.5-rc1#date-only
func wasmexport_DateOnly() (result *string) {
	result_ := Exports.DateOnly()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#time-only
//export jcbhmr:go/time@1.24.5-rc1#time-only
func wasmexport_TimeOnly() (result *string) {
	result_ := Exports.TimeOnly()
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#nanosecond
//export jcbhmr:go/time@1.24.5-rc1#nanosecond
func wasmexport_Nanosecond() (result0 uint64) {
	result := Exports.Nanosecond()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#microsecond
//export jcbhmr:go/time@1.24.5-rc1#microsecond
func wasmexport_Microsecond() (result0 uint64) {
	result := Exports.Microsecond()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#millisecond
//export jcbhmr:go/time@1.24.5-rc1#millisecond
func wasmexport_Millisecond() (result0 uint64) {
	result := Exports.Millisecond()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#second
//export jcbhmr:go/time@1.24.5-rc1#second
func wasmexport_Second() (result0 uint64) {
	result := Exports.Second()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#minute
//export jcbhmr:go/time@1.24.5-rc1#minute
func wasmexport_Minute() (result0 uint64) {
	result := Exports.Minute()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#hour
//export jcbhmr:go/time@1.24.5-rc1#hour
func wasmexport_Hour() (result0 uint64) {
	result := Exports.Hour()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#sleep
//export jcbhmr:go/time@1.24.5-rc1#sleep
func wasmexport_Sleep(d0 uint64) {
	d := (Duration)((uint64)(d0))
	Exports.Sleep(d)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#parse-duration
//export jcbhmr:go/time@1.24.5-rc1#parse-duration
func wasmexport_ParseDuration(s0 *uint8, s1 uint32) (result *cm.Result[int64, Duration, Error]) {
	s := cm.LiftString[string]((*uint8)(s0), (uint32)(s1))
	result_ := Exports.ParseDuration(s)
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#since
//export jcbhmr:go/time@1.24.5-rc1#since
func wasmexport_Since(t0 uint32) (result0 uint64) {
	t := cm.Reinterpret[Time]((uint32)(t0))
	result := Exports.Since(t)
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#until
//export jcbhmr:go/time@1.24.5-rc1#until
func wasmexport_Until(t0 uint32) (result0 uint64) {
	t := cm.Reinterpret[Time]((uint32)(t0))
	result := Exports.Until(t)
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-abs
//export jcbhmr:go/time@1.24.5-rc1#duration-abs
func wasmexport_DurationAbs(self0 uint64) (result0 uint64) {
	self := (Duration)((uint64)(self0))
	result := Exports.DurationAbs(self)
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-hours
//export jcbhmr:go/time@1.24.5-rc1#duration-hours
func wasmexport_DurationHours(self0 uint64) (result0 float64) {
	self := (Duration)((uint64)(self0))
	result := Exports.DurationHours(self)
	result0 = (float64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-microseconds
//export jcbhmr:go/time@1.24.5-rc1#duration-microseconds
func wasmexport_DurationMicroseconds(self0 uint64) (result0 uint64) {
	self := (Duration)((uint64)(self0))
	result := Exports.DurationMicroseconds(self)
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-milliseconds
//export jcbhmr:go/time@1.24.5-rc1#duration-milliseconds
func wasmexport_DurationMilliseconds(self0 uint64) (result0 uint64) {
	self := (Duration)((uint64)(self0))
	result := Exports.DurationMilliseconds(self)
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-minutes
//export jcbhmr:go/time@1.24.5-rc1#duration-minutes
func wasmexport_DurationMinutes(self0 uint64) (result0 float64) {
	self := (Duration)((uint64)(self0))
	result := Exports.DurationMinutes(self)
	result0 = (float64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-nanoseconds
//export jcbhmr:go/time@1.24.5-rc1#duration-nanoseconds
func wasmexport_DurationNanoseconds(self0 uint64) (result0 uint64) {
	self := (Duration)((uint64)(self0))
	result := Exports.DurationNanoseconds(self)
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-round
//export jcbhmr:go/time@1.24.5-rc1#duration-round
func wasmexport_DurationRound(self0 uint64, m0 uint64) (result0 uint64) {
	self := (Duration)((uint64)(self0))
	m := (Duration)((uint64)(m0))
	result := Exports.DurationRound(self, m)
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-seconds
//export jcbhmr:go/time@1.24.5-rc1#duration-seconds
func wasmexport_DurationSeconds(self0 uint64) (result0 float64) {
	self := (Duration)((uint64)(self0))
	result := Exports.DurationSeconds(self)
	result0 = (float64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-string
//export jcbhmr:go/time@1.24.5-rc1#duration-string
func wasmexport_DurationString(self0 uint64) (result *string) {
	self := (Duration)((uint64)(self0))
	result_ := Exports.DurationString(self)
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#duration-truncate
//export jcbhmr:go/time@1.24.5-rc1#duration-truncate
func wasmexport_DurationTruncate(self0 uint64, m0 uint64) (result0 uint64) {
	self := (Duration)((uint64)(self0))
	m := (Duration)((uint64)(m0))
	result := Exports.DurationTruncate(self, m)
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#local
//export jcbhmr:go/time@1.24.5-rc1#local
func wasmexport_Local() (result0 uint32) {
	result := Exports.Local()
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#UTC
//export jcbhmr:go/time@1.24.5-rc1#UTC
func wasmexport_UTC() (result0 uint32) {
	result := Exports.UTC()
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#fixed-zone
//export jcbhmr:go/time@1.24.5-rc1#fixed-zone
func wasmexport_FixedZone(name0 *uint8, name1 uint32, offset0 uint32) (result0 uint32) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	offset := (int32)((uint32)(offset0))
	result := Exports.FixedZone(name, offset)
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#load-location
//export jcbhmr:go/time@1.24.5-rc1#load-location
func wasmexport_LoadLocation(name0 *uint8, name1 uint32) (result *cm.Result[Location, Location, Error]) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	result_ := Exports.LoadLocation(name)
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#load-location-from-TZ-data
//export jcbhmr:go/time@1.24.5-rc1#load-location-from-TZ-data
func wasmexport_LoadLocationFromTZData(name0 *uint8, name1 uint32, data0 *uint8, data1 uint32) (result *cm.Result[Location, Location, Error]) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	data := cm.LiftList[cm.List[uint8]]((*uint8)(data0), (uint32)(data1))
	result_ := Exports.LoadLocationFromTZData(name, data)
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#january
//export jcbhmr:go/time@1.24.5-rc1#january
func wasmexport_January() (result0 uint32) {
	result := Exports.January()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#february
//export jcbhmr:go/time@1.24.5-rc1#february
func wasmexport_February() (result0 uint32) {
	result := Exports.February()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#march
//export jcbhmr:go/time@1.24.5-rc1#march
func wasmexport_March() (result0 uint32) {
	result := Exports.March()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#april
//export jcbhmr:go/time@1.24.5-rc1#april
func wasmexport_April() (result0 uint32) {
	result := Exports.April()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#may
//export jcbhmr:go/time@1.24.5-rc1#may
func wasmexport_May() (result0 uint32) {
	result := Exports.May()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#june
//export jcbhmr:go/time@1.24.5-rc1#june
func wasmexport_June() (result0 uint32) {
	result := Exports.June()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#july
//export jcbhmr:go/time@1.24.5-rc1#july
func wasmexport_July() (result0 uint32) {
	result := Exports.July()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#august
//export jcbhmr:go/time@1.24.5-rc1#august
func wasmexport_August() (result0 uint32) {
	result := Exports.August()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#september
//export jcbhmr:go/time@1.24.5-rc1#september
func wasmexport_September() (result0 uint32) {
	result := Exports.September()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#october
//export jcbhmr:go/time@1.24.5-rc1#october
func wasmexport_October() (result0 uint32) {
	result := Exports.October()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#november
//export jcbhmr:go/time@1.24.5-rc1#november
func wasmexport_November() (result0 uint32) {
	result := Exports.November()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#december
//export jcbhmr:go/time@1.24.5-rc1#december
func wasmexport_December() (result0 uint32) {
	result := Exports.December()
	result0 = (uint32)(result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#month-string
//export jcbhmr:go/time@1.24.5-rc1#month-string
func wasmexport_MonthString(self0 uint32) (result *string) {
	self := (Month)((uint32)(self0))
	result_ := Exports.MonthString(self)
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#date
//export jcbhmr:go/time@1.24.5-rc1#date
func wasmexport_Date(year0 uint32, month0 uint32, day0 uint32, hour0 uint32, min0 uint32, sec0 uint32, nsec0 uint32, loc0 uint32) (result0 uint32) {
	year := (int32)((uint32)(year0))
	month := (Month)((uint32)(month0))
	day := (int32)((uint32)(day0))
	hour := (int32)((uint32)(hour0))
	min_ := (int32)((uint32)(min0))
	sec := (int32)((uint32)(sec0))
	nsec := (int32)((uint32)(nsec0))
	loc := cm.Reinterpret[Location]((uint32)(loc0))
	result := Exports.Date(year, month, day, hour, min_, sec, nsec, loc)
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#now
//export jcbhmr:go/time@1.24.5-rc1#now
func wasmexport_Now() (result0 uint32) {
	result := Exports.Now()
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#parse
//export jcbhmr:go/time@1.24.5-rc1#parse
func wasmexport_Parse(layout0 *uint8, layout1 uint32, value0 *uint8, value1 uint32) (result *cm.Result[Time, Time, Error]) {
	layout := cm.LiftString[string]((*uint8)(layout0), (uint32)(layout1))
	value := cm.LiftString[string]((*uint8)(value0), (uint32)(value1))
	result_ := Exports.Parse(layout, value)
	result = &result_
	return
}

//go:wasmexport jcbhmr:go/time@1.24.5-rc1#parse-in-location
//export jcbhmr:go/time@1.24.5-rc1#parse-in-location
func wasmexport_ParseInLocation(layout0 *uint8, layout1 uint32, value0 *uint8, value1 uint32, loc0 uint32) (result *cm.Result[Time, Time, Error]) {
	layout := cm.LiftString[string]((*uint8)(layout0), (uint32)(layout1))
	value := cm.LiftString[string]((*uint8)(value0), (uint32)(value1))
	loc := cm.Reinterpret[Location]((uint32)(loc0))
	result_ := Exports.ParseInLocation(layout, value, loc)
	result = &result_
	return
}
