// Code generated by wit-bindgen-go. DO NOT EDIT.

package time

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "jcbhmr:go/time@1.24.5-rc1".
var Exports struct {
	// Location represents the caller-defined exports for resource "jcbhmr:go/time@1.24.5-rc1#location".
	Location struct {
		// Destructor represents the caller-defined, exported destructor for resource "location".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Constructor represents the caller-defined, exported constructor for resource "location".
		//
		//	constructor()
		Constructor func() (result Location)

		// String represents the caller-defined, exported method "string".
		//
		// String returns a descriptive name for the time zone information, corresponding
		// to the name argument to LoadLocation or FixedZone.
		//
		//	%string: func() -> string
		String func(self cm.Rep) (result string)
	}

	// Time represents the caller-defined exports for resource "jcbhmr:go/time@1.24.5-rc1#time".
	Time struct {
		// Destructor represents the caller-defined, exported destructor for resource "time".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// ExportConstructor represents the caller-defined, exported constructor for resource "time".
		//
		//	constructor()
		ExportConstructor func() (result Time)

		// Format represents the caller-defined, exported method "format".
		//
		//	format: func(layout: string) -> string
		Format func(self cm.Rep, layout string) (result string)
	}

	// Layout represents the caller-defined, exported function "layout".
	//
	// The reference time, in numerical order.
	//
	//	layout: func() -> string
	Layout func() (result string)

	// ANSIC represents the caller-defined, exported function "ANSIC".
	//
	//	ANSIC: func() -> string
	ANSIC func() (result string)

	// UnixDate represents the caller-defined, exported function "unix-date".
	//
	//	unix-date: func() -> string
	UnixDate func() (result string)

	// RubyDate represents the caller-defined, exported function "ruby-date".
	//
	//	ruby-date: func() -> string
	RubyDate func() (result string)

	// RFC822 represents the caller-defined, exported function "RFC822".
	//
	//	RFC822: func() -> string
	RFC822 func() (result string)

	// RFC822Z represents the caller-defined, exported function "RFC822Z".
	//
	// RFC822 with numeric zone
	//
	//	RFC822Z: func() -> string
	RFC822Z func() (result string)

	// RFC850 represents the caller-defined, exported function "RFC850".
	//
	//	RFC850: func() -> string
	RFC850 func() (result string)

	// RFC1123 represents the caller-defined, exported function "RFC1123".
	//
	//	RFC1123: func() -> string
	RFC1123 func() (result string)

	// RFC1123Z represents the caller-defined, exported function "RFC1123Z".
	//
	// RFC1123 with numeric zone
	//
	//	RFC1123Z: func() -> string
	RFC1123Z func() (result string)

	// RFC3339 represents the caller-defined, exported function "RFC3339".
	//
	//	RFC3339: func() -> string
	RFC3339 func() (result string)

	// RFC3339Nano represents the caller-defined, exported function "RFC3339-nano".
	//
	//	RFC3339-nano: func() -> string
	RFC3339Nano func() (result string)

	// Kitchen represents the caller-defined, exported function "kitchen".
	//
	//	kitchen: func() -> string
	Kitchen func() (result string)

	// Stamp represents the caller-defined, exported function "stamp".
	//
	//	stamp: func() -> string
	Stamp func() (result string)

	// StampMilli represents the caller-defined, exported function "stamp-milli".
	//
	//	stamp-milli: func() -> string
	StampMilli func() (result string)

	// StampMicro represents the caller-defined, exported function "stamp-micro".
	//
	//	stamp-micro: func() -> string
	StampMicro func() (result string)

	// StampNano represents the caller-defined, exported function "stamp-nano".
	//
	//	stamp-nano: func() -> string
	StampNano func() (result string)

	// DateTime represents the caller-defined, exported function "date-time".
	//
	//	date-time: func() -> string
	DateTime func() (result string)

	// DateOnly represents the caller-defined, exported function "date-only".
	//
	//	date-only: func() -> string
	DateOnly func() (result string)

	// TimeOnly represents the caller-defined, exported function "time-only".
	//
	//	time-only: func() -> string
	TimeOnly func() (result string)

	// Nanosecond represents the caller-defined, exported function "nanosecond".
	//
	//	nanosecond: func() -> duration
	Nanosecond func() (result Duration)

	// Microsecond represents the caller-defined, exported function "microsecond".
	//
	//	microsecond: func() -> duration
	Microsecond func() (result Duration)

	// Millisecond represents the caller-defined, exported function "millisecond".
	//
	//	millisecond: func() -> duration
	Millisecond func() (result Duration)

	// Second represents the caller-defined, exported function "second".
	//
	//	second: func() -> duration
	Second func() (result Duration)

	// Minute represents the caller-defined, exported function "minute".
	//
	//	minute: func() -> duration
	Minute func() (result Duration)

	// Hour represents the caller-defined, exported function "hour".
	//
	//	hour: func() -> duration
	Hour func() (result Duration)

	// Sleep represents the caller-defined, exported function "sleep".
	//
	// after: func(d: duration) -> chan<time>;
	// Sleep pauses the current goroutine for at least the duration d. A negative or zero
	// duration causes Sleep to return immediately.
	//
	//	sleep: func(d: duration)
	Sleep func(d Duration)

	// ParseDuration represents the caller-defined, exported function "parse-duration".
	//
	// ParseDuration parses a duration string. A duration string is a possibly signed
	// sequence of decimal numbers, each with optional fraction and a unit suffix, such
	// as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms",
	// "s", "m", "h".
	//
	//	parse-duration: func(s: string) -> result<duration, error>
	ParseDuration func(s string) (result cm.Result[int64, Duration, Error])

	// Since represents the caller-defined, exported function "since".
	//
	// Since returns the time elapsed since t. It is shorthand for time.Now().Sub(t).
	//
	//	since: func(t: time) -> duration
	Since func(t Time) (result Duration)

	// Until represents the caller-defined, exported function "until".
	//
	// Until returns the duration until t. It is shorthand for t.Sub(time.Now()).
	//
	//	until: func(t: time) -> duration
	Until func(t Time) (result Duration)

	// DurationAbs represents the caller-defined, exported function "duration-abs".
	//
	// Abs returns the absolute value of d. As a special case, Duration(math.MinInt64)
	// is converted to Duration(math.MaxInt64), reducing its magnitude by 1 nanosecond.
	//
	//	duration-abs: func() -> duration
	DurationAbs func(self Duration) (result Duration)

	// DurationHours represents the caller-defined, exported function "duration-hours".
	//
	// Hours returns the duration as a floating point number of hours.
	//
	//	duration-hours: func() -> f64
	DurationHours func(self Duration) (result float64)

	// DurationMicroseconds represents the caller-defined, exported function "duration-microseconds".
	//
	// Microseconds returns the duration as an integer microsecond count.
	//
	//	duration-microseconds: func() -> s64
	DurationMicroseconds func(self Duration) (result int64)

	// DurationMilliseconds represents the caller-defined, exported function "duration-milliseconds".
	//
	// Milliseconds returns the duration as an integer millisecond count.
	//
	//	duration-milliseconds: func() -> s64
	DurationMilliseconds func(self Duration) (result int64)

	// DurationMinutes represents the caller-defined, exported function "duration-minutes".
	//
	// Minutes returns the duration as a floating point number of minutes.
	//
	//	duration-minutes: func() -> f64
	DurationMinutes func(self Duration) (result float64)

	// DurationNanoseconds represents the caller-defined, exported function "duration-nanoseconds".
	//
	// Nanoseconds returns the duration as an integer nanosecond count.
	//
	//	duration-nanoseconds: func() -> s64
	DurationNanoseconds func(self Duration) (result int64)

	// DurationRound represents the caller-defined, exported function "duration-round".
	//
	// Round returns the result of rounding d to the nearest multiple of m. The rounding
	// behavior for halfway values is to round away from zero. If the result exceeds the
	// maximum (or minimum) value that can be stored in a Duration, Round returns the
	// maximum (or minimum) duration. If m <= 0, Round returns d unchanged.
	//
	//	duration-round: func(m: duration) -> duration
	DurationRound func(self Duration, m Duration) (result Duration)

	// DurationSeconds represents the caller-defined, exported function "duration-seconds".
	//
	// Seconds returns the duration as a floating point number of seconds.
	//
	//	duration-seconds: func() -> f64
	DurationSeconds func(self Duration) (result float64)

	// DurationString represents the caller-defined, exported function "duration-string".
	//
	// String returns a string representing the duration in the form "72h3m0.5s". Leading
	// zero units are omitted. As a special case, durations less than one second format
	// use a smaller unit (milli-, micro-, or nanoseconds) to ensure that the leading
	// digit is non-zero. The zero duration formats as 0s.
	//
	//	duration-string: func() -> string
	DurationString func(self Duration) (result string)

	// DurationTruncate represents the caller-defined, exported function "duration-truncate".
	//
	// Truncate returns the result of rounding d toward zero to a multiple of m. If m
	// <= 0, Truncate returns d unchanged.
	//
	//	duration-truncate: func(m: duration) -> duration
	DurationTruncate func(self Duration, m Duration) (result Duration)

	// Local represents the caller-defined, exported function "local".
	//
	// Local represents the system's local time zone. On Unix systems, Local consults
	// the TZ environment variable to find the time zone to use. No TZ means use the system
	// default /etc/localtime. TZ="" means use UTC. TZ="foo" means use file foo in the
	// system timezone directory.
	//
	//	local: func() -> location
	Local func() (result Location)

	// UTC represents the caller-defined, exported function "UTC".
	//
	// UTC represents Universal Coordinated Time (UTC).
	//
	//	UTC: func() -> location
	UTC func() (result Location)

	// FixedZone represents the caller-defined, exported function "fixed-zone".
	//
	// FixedZone returns a Location that always uses the given zone name and offset (seconds
	// east of UTC).
	//
	//	fixed-zone: func(name: string, offset: s32) -> location
	FixedZone func(name string, offset int32) (result Location)

	// LoadLocation represents the caller-defined, exported function "load-location".
	//
	// LoadLocation returns the Location with the given name.
	//
	// If the name is "" or "UTC", LoadLocation returns UTC. If the name is "Local", LoadLocation
	// returns Local.
	//
	// Otherwise, the name is taken to be a location name corresponding to a file in the
	// IANA Time Zone database, such as "America/New_York".
	//
	// LoadLocation looks for the IANA Time Zone database in the following locations in
	// order:
	//
	// - the directory or uncompressed zip file named by the ZONEINFO environment variable
	// - on a Unix system, the system standard installation location
	// - $GOROOT/lib/time/zoneinfo.zip
	// - the time/tzdata package, if it was imported
	//
	//	load-location: func(name: string) -> result<location, error>
	LoadLocation func(name string) (result cm.Result[Location, Location, Error])

	// LoadLocationFromTZData represents the caller-defined, exported function "load-location-from-TZ-data".
	//
	// LoadLocationFromTZData returns a Location with the given name initialized from
	// the IANA Time Zone database-formatted data. The data should be in the format of
	// a standard IANA time zone file (for example, the content of /etc/localtime on Unix
	// systems).
	//
	//	load-location-from-TZ-data: func(name: string, data: list<u8>) -> result<location,
	//	error>
	LoadLocationFromTZData func(name string, data cm.List[uint8]) (result cm.Result[Location, Location, Error])

	// January represents the caller-defined, exported function "january".
	//
	//	january: func() -> month
	January func() (result Month)

	// February represents the caller-defined, exported function "february".
	//
	//	february: func() -> month
	February func() (result Month)

	// March represents the caller-defined, exported function "march".
	//
	//	march: func() -> month
	March func() (result Month)

	// April represents the caller-defined, exported function "april".
	//
	//	april: func() -> month
	April func() (result Month)

	// May represents the caller-defined, exported function "may".
	//
	//	may: func() -> month
	May func() (result Month)

	// June represents the caller-defined, exported function "june".
	//
	//	june: func() -> month
	June func() (result Month)

	// July represents the caller-defined, exported function "july".
	//
	//	july: func() -> month
	July func() (result Month)

	// August represents the caller-defined, exported function "august".
	//
	//	august: func() -> month
	August func() (result Month)

	// September represents the caller-defined, exported function "september".
	//
	//	september: func() -> month
	September func() (result Month)

	// October represents the caller-defined, exported function "october".
	//
	//	october: func() -> month
	October func() (result Month)

	// November represents the caller-defined, exported function "november".
	//
	//	november: func() -> month
	November func() (result Month)

	// December represents the caller-defined, exported function "december".
	//
	//	december: func() -> month
	December func() (result Month)

	// MonthString represents the caller-defined, exported function "month-string".
	//
	// String returns the English name of the month ("January", "February", ...).
	//
	//	month-string: func() -> string
	MonthString func(self Month) (result string)

	// Date represents the caller-defined, exported function "date".
	//
	// # Date returns the Time corresponding to
	//
	// yyyy-mm-dd hh:mm:ss + nsec nanoseconds
	//
	// in the appropriate zone for that time in the given location.
	//
	// The month, day, hour, min, sec, and nsec values may be outside their usual ranges
	// and will be normalized during the conversion. For example, October 32 converts
	// to November 1.
	//
	// A daylight savings time transition skips or repeats times. For example, in the
	// United States, March 13, 2011 2:15am never occurred, while November 6, 2011 1:15am
	// occurred twice. In such cases, the choice of time zone, and therefore the time,
	// is not well-defined. Date returns a time that is correct in one of the two zones
	// involved in the transition, but it does not guarantee which.
	//
	// Date panics if loc is nil.
	//
	//	date: func(year: s32, month: month, day: s32, hour: s32, min: s32, sec: s32, nsec:
	//	s32, loc: location) -> time
	Date func(year int32, month Month, day int32, hour int32, min_ int32, sec int32, nsec int32, loc Location) (result Time)

	// Now represents the caller-defined, exported function "now".
	//
	// Now returns the current local time.
	//
	//	now: func() -> time
	Now func() (result Time)

	// Parse represents the caller-defined, exported function "parse".
	//
	// Parse parses a formatted string and returns the time value it represents. See the
	// documentation for the constant called Layout to see how to represent the format.
	// The second argument must be parseable using the format string (layout) provided
	// as the first argument.
	//
	// The example for Time.Format demonstrates the working of the layout string in detail
	// and is a good reference.
	//
	// When parsing (only), the input may contain a fractional second field immediately
	// after the seconds field, even if the layout does not signify its presence. In that
	// case either a comma or a decimal point followed by a maximal series of digits is
	// parsed as a fractional second. Fractional seconds are truncated to nanosecond precision.
	//
	// Elements omitted from the layout are assumed to be zero or, when zero is impossible,
	// one, so parsing "3:04pm" returns the time corresponding to Jan 1, year 0, 15:04:00
	// UTC (note that because the year is 0, this time is before the zero Time). Years
	// must be in the range 0000..9999. The day of the week is checked for syntax but
	// it is otherwise ignored.
	//
	// For layouts specifying the two-digit year 06, a value NN >= 69 will be treated
	// as 19NN and a value NN < 69 will be treated as 20NN.
	//
	// The remainder of this comment describes the handling of time zones.
	//
	// In the absence of a time zone indicator, Parse returns a time in UTC.
	//
	// When parsing a time with a zone offset like -0700, if the offset corresponds to
	// a time zone used by the current location (Local), then Parse uses that location
	// and zone in the returned time. Otherwise it records the time as being in a fabricated
	// location with time fixed at the given zone offset.
	//
	// When parsing a time with a zone abbreviation like MST, if the zone abbreviation
	// has a defined offset in the current location, then that offset is used. The zone
	// abbreviation "UTC" is recognized as UTC regardless of location. If the zone abbreviation
	// is unknown, Parse records the time as being in a fabricated location with the given
	// zone abbreviation and a zero offset. This choice means that such a time can be
	// parsed and reformatted with the same layout losslessly, but the exact instant used
	// in the representation will differ by the actual zone offset. To avoid such problems,
	// prefer time layouts that use a numeric zone offset, or use ParseInLocation.
	//
	//	parse: func(layout: string, value: string) -> result<time, error>
	Parse func(layout string, value string) (result cm.Result[Time, Time, Error])

	// ParseInLocation represents the caller-defined, exported function "parse-in-location".
	//
	// ParseInLocation is like Parse but differs in two important ways. First, in the
	// absence of time zone information, Parse interprets a time as UTC; ParseInLocation
	// interprets the time as in the given location. Second, when given a zone offset
	// or abbreviation, Parse tries to match it against the Local location; ParseInLocation
	// uses the given location.
	//
	//	parse-in-location: func(layout: string, value: string, loc: location) -> result<time,
	//	error>
	ParseInLocation func(layout string, value string, loc Location) (result cm.Result[Time, Time, Error])
}
