// Code generated by wit-bindgen-go. DO NOT EDIT.

package builtin

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "jcbhmr:go@1.24.5-rc1".

//go:wasmimport [export]jcbhmr:go/builtin@1.24.5-rc1 [resource-new]error
//go:noescape
func wasmimport_ErrorResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]jcbhmr:go/builtin@1.24.5-rc1 [resource-rep]error
//go:noescape
func wasmimport_ErrorResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]jcbhmr:go/builtin@1.24.5-rc1 [resource-drop]error
//go:noescape
func wasmimport_ErrorResourceDrop(self0 uint32)

//go:wasmexport jcbhmr:go/builtin@1.24.5-rc1#[dtor]error
//export jcbhmr:go/builtin@1.24.5-rc1#[dtor]error
func wasmexport_ErrorDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.Error.Destructor(self)
	return
}

//go:wasmexport jcbhmr:go/builtin@1.24.5-rc1#[method]error.error2
//export jcbhmr:go/builtin@1.24.5-rc1#[method]error.error2
func wasmexport_ErrorError2(self0 uint32) (result *string) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	result_ := Exports.Error.Error2(self)
	result = &result_
	return
}
