// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package builtin represents the exported interface "jcbhmr:go/builtin@1.24.5-rc1".
package builtin

import (
	"go.bytecodealliance.org/cm"
)

// Error represents the exported resource "jcbhmr:go/builtin@1.24.5-rc1#error".
//
//	resource error
type Error cm.Resource

// ErrorResourceNew represents the imported resource-new for resource "error".
//
// Creates a new resource handle.
//
//go:nosplit
func ErrorResourceNew(rep cm.Rep) (result Error) {
	rep0 := cm.Reinterpret[uint32](rep)
	result0 := wasmimport_ErrorResourceNew((uint32)(rep0))
	result = cm.Reinterpret[Error]((uint32)(result0))
	return
}

// ResourceRep represents the imported resource-rep for resource "error".
//
// Returns the underlying resource representation.
//
//go:nosplit
func (self Error) ResourceRep() (result cm.Rep) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_ErrorResourceRep((uint32)(self0))
	result = cm.Reinterpret[cm.Rep]((uint32)(result0))
	return
}

// ResourceDrop represents the imported resource-drop for resource "error".
//
// Drops a resource handle.
//
//go:nosplit
func (self Error) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ErrorResourceDrop((uint32)(self0))
	return
}

func init() {
	Exports.Error.Destructor = func(self cm.Rep) {}
}
