// Code generated by wit-bindgen-go. DO NOT EDIT.

package builtin

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "jcbhmr:go/builtin@1.24.5-rc1".
var Exports struct {
	// Error represents the caller-defined exports for resource "jcbhmr:go/builtin@1.24.5-rc1#error".
	Error struct {
		// Destructor represents the caller-defined, exported destructor for resource "error".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Error2 represents the caller-defined, exported method "error2".
		//
		// For some reason the wit-bindgen-go tool chokes when this function is named "error".
		//
		//	error2: func() -> string
		Error2 func(self cm.Rep) (result string)
	}
}
